name: oneiros::pr_checks

on:
  pull_request:
    branches:
      - dev
      - dev/*
      - main
      - main/*

jobs:
  run-build:
    name: oneiros::pr_checks::build
    runs-on: ubuntu-latest

    steps:
      - name: oneiros::pr_checks::build::Check out Git repository
        uses: actions/checkout@v3

      - name: oneiros::pr_checks::build::Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: oneiros::pr_checks::build::Install Node.js dependencies
        run: npm ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: oneiros::pr_checks::build::Build
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  run-lint:
    name: oneiros::pr_checks::lint
    runs-on: ubuntu-latest

    steps:
      - name: oneiros::pr_checks::lint::Check out Git repository
        uses: actions/checkout@v3

      - name: oneiros::pr_checks::lint::Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20

      # ESLint and Prettier must be in `package.json`
      - name: oneiros::pr_checks::lint::Install Node.js dependencies
        run: npm ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: oneiros::pr_checks::lint::Run linters
        run: npm run ci:format

  run-test:
      name: oneiros::pr_checks::test
      runs-on: ubuntu-latest

      steps:
        - name: oneiros::pr_checks::test::Check out Git repository
          uses: actions/checkout@v3

        - name: oneiros::pr_checks::test::Set up Node.js
          uses: actions/setup-node@v1
          with:
            node-version: 20

        # ESLint and Prettier must be in `package.json`
        - name: oneiros::pr_checks::test::Install Node.js dependencies
          run: npm ci
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: oneiros::pr_checks::test::Run tests
          run: npm run test